### ISSUE TITLE
Update Hacktoberfest 2021 Repos For Hacktoberfest 2022

### ISSUE THREAD

**Issue by Bobliuuu** [vivian-dai/Hacktoberfest-2022-Repos#112]
Go through the current Hacktoberfest active repos, and move any inactive or not tagged repos (without the hacktoberfest-2022 tag) to the inactive or invalid list.

**Comment by vivian-dai** [comment]
@chiragkhatri19 you can just take the issue. If the issue is broad enough (like this one) anyone can take it. I will only be assigning specific issues

**Comment by chiragkhatri19** [comment]
Got it @vivian-dai

**Comment by Nithin108** [comment]
assign this to me please

**Comment by vivian-dai** [comment]
@Nithin108 just take the issue, see comment above
