### ISSUE TITLE
Add Description to repositories without descriptions

### ISSUE THREAD

**Issue by vivian-dai** [vivian-dai/Hacktoberfest-2022-Repos#117]
Quickly look through some repositories that don't have a description on it, figure out what the repository is doing, then write in a description

**Comment by BTANISHA11** [comment]
can you pls assign this to me

**Comment by vivian-dai** [comment]
@BTANISHA11 you can just take it, there aren't too many repositories to go through

**Comment by BTANISHA11** [comment]
okk thanks

**Comment by Bobliuuu** [comment]
@vivian-dai This issue can be closed for now.

**Comment by rajbhoyar729** [comment]
i  had  made a commit  can  u please  check it  out

**Comment by BTANISHA11** [comment]
@vivian-dai its showing excluded from hactoberfest 2022 can you pls resolve the isuue
