### ISSUE TITLE
Order the repositories within a table in alphabetical order

### ISSUE THREAD

**Issue by vivian-dai** [vivian-dai/Hacktoberfest-2022-Repos#118]
Eg.
|||
|-|-|
|owner/repo|description|
|aaa/aaa|desc| 

should be 

|||
|-|-|
|aaa/aaa|desc|
|owner/repo|description|

**Comment by Rounak-28** [comment]
@vivian-dai  can I work in this?

**Comment by vivian-dai** [comment]
@Rounak-28 yes you can, go ahead!
