### ISSUE TITLE
Go through all the repositories and move any excluded ones into the blacklist

### ISSUE THREAD

**Issue by vivian-dai** [vivian-dai/Hacktoberfest-2022-Repos#122]
You can add a comment if this seems unclear

**Comment by rajbhoyar729** [comment]
can u please  explain
bro

**Comment by vivian-dai** [comment]
If any of the repositories state they were excluded, remove them and add to the blacklist

**Comment by rajbhoyar729** [comment]
ok

**Comment by amyra98** [comment]
@vivian-dai can you assign me this issue and also tell how to check if a repo is excluded?
