### ISSUE TITLE
Change 2021 to 2022 in the yaml file

### ISSUE THREAD

**Issue by vivian-dai** [vivian-dai/Hacktoberfest-2022-Repos#125]
Head over to [`config.yml`](https://github.com/vivian-dai/Hacktoberfest-2022-Repos/blob/main/_config.yml) and change all instances of "2021" to "2022"

**Comment by Sarabjeet108** [comment]
Would like to work on the issue. please assign it to me.

**Comment by rajbhoyar729** [comment]
i  have  done  the  changes
