### ISSUE TITLE
Go through the repositories and remove and that don't have a "hacktoberfest" label

### ISSUE THREAD

**Issue by vivian-dai** [vivian-dai/Hacktoberfest-2022-Repos#136]
Comment below if you have any questions

**Comment by vaibhavmishra4g** [comment]
Could you assign me this?

**Comment by vaibhavmishra4g** [comment]
how we can check label in repo?

**Comment by vivian-dai** [comment]
@vaibhavmishra4g if the repository's about shows "hacktoberfest" as a topic, eg. 
![image](https://user-images.githubusercontent.com/38384400/193471812-32710c5e-595b-4eef-8b8b-95dcb6b47766.png)
then it has a "hacktoberfest" label. If not, it doesn't

**Comment by vaibhavmishra4g** [comment]
ok I'll update you in a while

**Comment by vaibhavmishra4g** [comment]
can i know how to remove repo?

**Comment by vaibhavmishra4g** [comment]
Done!Thanks for giving me the opportunity!

**Comment by vaibhavmishra4g** [comment]
hey my pr didn't got accepted into hacktoberfest can you please help?

**Comment by vivian-dai** [comment]
@vaibhavmishra4g turns out this repository got excluded
