### ISSUE TITLE
some repos are outdated not actively merging PRs

### ISSUE THREAD

**Issue by jatt7568** [vivian-dai/Hacktoberfest-2022-Repos#144]
some repos are outdated and not actively merging open pull requests in hacktoberfest 2022. I have seen many repos you mentioned are last updated in oct 2021 ..(hacktoberfest 2021). we might remove them?? or add updated repos? @vivian-dai

**Comment by vivian-dai** [comment]
If there exists a 2022 repo, you can update it to the 2022 one. Otherwise if it's been inactive for over two years, you can put it in the archive.
